services:
  - type: web
    name: django-portfolio
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn yourprojectname.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: yourprojectname.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
